### ISSUE TITLE
About concat two features from different conv layers

### ISSUE THREAD

**Issue by Zehaos** [77695/SA-Siam#2]
Could you please shed some light on how to concat two features(with different spatial resolution) from different layers? I could not find any detail in the paper, thanks.

**Comment by Zehaos** [comment]
Closed. Feature map of last two conv layer in Alexnet have the same size. So they can be concated.

**Comment by 77695** [comment]
Actually they are not the same size. Size of conv4 is 8x8. Size of conv5 is 6x6. Feature maps of conv5 are padded to 8x8 size with zero.

**Comment by Zehaos** [comment]
@77695 Thanks.
